### ISSUE TITLE
0.2.1 global log feature list

### ISSUE THREAD

**Issue by newwby** [newwby/ddat-gpf.core#13]
this is everything that wasn't finished in 0.2.0 (see #8)

### Task TODO
- [ ] Get Stack Trace as string method
- [ ] Log to File Method
- [ ] Log to File Settings (default to Always)
    - [ ] Log to File on Exit Notification implementation
    - [ ] Log to File interval implementation
- [ ] add set-permission method for INFO logs
- [ ] onExit prints all no-permission logging
- [ ] tracking total logging calls
- [ ] load user dict from res:// as json (once #12 is implemented)
- [ ] support null as replacement for caller arg (add as default)
- [ ] Asynchronous Logging Manager (logs send on idle console frames with timestamp)

### no longer planned
- [ ] Set Verbose Logging Permission (on a per script basis (uses self as key))
    - [ ] Errors always show, always push
    - [ ] Trace always show
    - [ ] Warn always show (or show with permission, exit log without?)
    - [ ] Info show with permission, exit log without

**Comment by newwby** [comment]
versioning update

**Comment by newwby** [comment]
add set-permission method for INFO logs > added permission logging for all

**Comment by newwby** [comment]
' Set Verbose Logging Permission' replaced with elevated logging behaviour in 94c3f75

**Comment by newwby** [comment]
e8a36e1 - 'Log to File interval implementation'
4692289 - completed 'Log to File Settings (default to Always)'

**Comment by newwby** [comment]
- [ ] #15 moved to #17
