### ISSUE TITLE
dev menus in globalDebug are broken

### ISSUE THREAD

**Issue by newwby** [newwby/ddat-gpf.core#16]
combining devtools and debug singletons has broken dev action menu functionality

### todo
- [x] restore devDebugOverlay function
- [x] restore devActionMenu previous function
- [x] update test for devDebugOverlay
- [x] update test for devActionMenu function

**Comment by newwby** [comment]
finished with 83fef1c
